# Generated by Django 6.0.7 on 2026-07-30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("cover_image", models.ImageField(blank=True, null=True, upload_to="event_covers/")),
                ("venue", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("category", models.CharField(max_length=100)),
                ("visibility", models.CharField(choices=[("public", "Public"), ("private", "Private")], default="public", max_length=10)),
                ("max_attendees", models.PositiveIntegerField(blank=True, null=True)),
                ("registration_deadline", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organizer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="organized_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("start_datetime", "id")},
        ),
        migrations.CreateModel(
            name="EventAttendee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(choices=[("going", "Going"), ("interested", "Interested")], default="going", max_length=12)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendances", to="events.event")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="event_attendances", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-joined_at",)},
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["start_datetime"], name="events_even_start_d_b72861_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["city", "category"], name="events_even_city_44aff2_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["organizer", "start_datetime"], name="events_even_organiz_3acda7_idx"),
        ),
        migrations.AddConstraint(
            model_name="eventattendee",
            constraint=models.UniqueConstraint(fields=("event", "user"), name="unique_event_attendee"),
        ),
    ]
